DROP TABLE IF EXISTS EMPLOYEE_USER;
DROP SEQUENCE IF EXISTS EMPLOYEE_USER_SEQ;

CREATE SEQUENCE EMPLOYEE_USER_SEQ;

CREATE TABLE IF NOT EXISTS EMPLOYEE_USER (

    ID BIGINT DEFAULT EMPLOYEE_USER_SEQ.nextval PRIMARY KEY,
    USER_ID VARCHAR(64) NOT NULL,
    LOGIN VARCHAR(64) NOT NULL,
    SALARY DECIMAL(10, 2) NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    constraint USER_ID_IDX unique (user_id),
    constraint LOGIN_IDX unique (login)
)

