DROP TABLE IF EXISTS EMPLOYEE_USER;
DROP SEQUENCE IF EXISTS EMPLOYEE_USER_SEQ;

CREATE SEQUENCE EMPLOYEE_USER_SEQ;

CREATE TABLE IF NOT EXISTS EMPLOYEE_USER (

    ID VARCHAR(64) NOT NULL PRIMARY KEY,
    LOGIN VARCHAR(64) NOT NULL,
    SALARY DECIMAL(10, 2) NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    constraint LOGIN_IDX unique (LOGIN)
)

